FROM python:slim
WORKDIR /app

RUN apt update && apt install -y postgresql-client

COPY requirements-consumer.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY rabbitmq.py rabbitmq.py
COPY consumer.py consumer.py
ENTRYPOINT ["python", "consumer.py"]
